version: '3.4'

services:

  eshopwcfservice:
    image: eshop/wcfservice:${TAG:-latest}
    build:
      context: ./deploy/wcf
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      
  eshop.modernized.mvc:
    image: eshop/modernizedmvc:${TAG:-latest}
    build:
      context: ./deploy/mvc
      dockerfile: Dockerfile
    depends_on:
      - sql.data      
    
  sql.data:
    image: hduong/mssql-server-2022-dev:2022